---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos65
    driver:
        box: learningchef/centos65
        boxurl: learningchef/centos65

suites:
  - name: default
    run_list:
    attributes:
